import { randomUUID } from "node:crypto"; import { startHeartbeat } from "./cloud"; import { PlannerEngine } from "./planner-engine";
function json(payload: unknown, status: number, headers?: Record<string, string>): Response { const body = JSON.stringify(payload); return new Response(body, { status, headers: { "content-type": "application/json; charset=utf-8", "x-request-id": randomUUID(), ...headers } }); }
export function createServer() { const port = Number(process.env.PORT || "3097"); const baseUrl = process.env.NEXUS_NEXUS_PLANNER_BASE_URL || `http://localhost:${port}`; const startedAt = Date.now(); const engine = new PlannerEngine("data/planner.sqlite");
  const server = Bun.serve({ port, async fetch(request) { const url = new URL(request.url); const path = url.pathname || "";
    if (request.method === "GET" && path === "/health") { return json({ service: "nexus-planner", status: "ok", version: "v1", uptimeSeconds: Math.floor((Date.now() - startedAt) / 1000), timestamp: new Date().toISOString() }, 200); }
    if (request.method === "GET" && path === "/api/v1/status") { return json({ service: "nexus-planner", status: "ready", capabilities: ["plans","tasks","scheduling"], cloudIntegration: { enabled: (process.env["NEXUS_PLANNER_ENABLE_CLOUD_INTEGRATION"] || "true") !== "false", cloudUrl: process.env.NEXUS_CLOUD_URL || "http://localhost:8787" } }, 200); }
    if (request.method === "GET" && path === "/api/v1/planner/plans") { const s = url.searchParams.get("status") || undefined; return json(engine.listPlans(s), 200); }
    if (request.method === "POST" && path === "/api/v1/planner/plans") { const b = await request.json().catch(() => ({})) as any; if (!b.title) return json({ error: "title required" }, 400); return json(engine.addPlan(b.title, b.description || "", b.startDate || "", b.endDate || ""), 201); }
    if (request.method === "GET" && path === "/api/v1/planner/plans/tasks") { const pid = url.searchParams.get("planId"); if (!pid) return json({ error: "planId required" }, 400); return json(engine.listPlanTasks(pid), 200); }
    if (request.method === "POST" && path === "/api/v1/planner/plans/tasks") { const b = await request.json().catch(() => ({})) as any; if (!b.planId || !b.title) return json({ error: "planId and title required" }, 400); return json(engine.addPlanTask(b.planId, b.title, b.dueDate || ""), 201); }
    const plm = path.match(/^\/api\/v1\/planner\/plans\/([^/]+)$/); if (request.method === "GET" && plm) { const p = engine.getPlan(plm[1]!); return p ? json(p, 200) : json({ error: "not found" }, 404); }
    return json({ error: "not found" }, 404); } });
  console.log(`[nexus-planner] Listening on port ${server.port}`); const stopHeartbeat = startHeartbeat(baseUrl); return { server, engine, close: () => { stopHeartbeat(); server.stop(); } }; }
