#!/usr/bin/env bash
# Nexus Systems — Deploy Installer
# Copies systemd units, generates .env, creates data dirs, optionally starts.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY="$ROOT/deploy"
SYSTEMD_DIR="$DEPLOY/systemd"
ENV_FILE="$ROOT/.env"
ENV_EXAMPLE="$ROOT/env.example"
DATA_DIR="$ROOT/data"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[nexus-deploy]${NC} $*"; }
warn() { echo -e "${YELLOW}[nexus-deploy] WARN:${NC} $*"; }
err()  { echo -e "${RED}[nexus-deploy] ERROR:${NC} $*" >&2; }

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Install systemd units, generate .env, set up data directories, and optionally
start the Nexus Systems ecosystem.

Options:
  --prefix DIR      Install prefix for systemd units (default: /etc/systemd/system)
  --user USER       User for systemd services (default: current user)
  --group GROUP     Group for systemd services (default: current group)
  --workdir DIR     WorkingDirectory for services (default: this repo root)
  --env-only        Only generate .env, skip systemd installation
  --no-start        Do not start services after installation
  --help            Show this help

Environment variables (for .env generation):
  NEXUS_CLOUD_API_KEY     API key for Nexus-Cloud (default: change-me)
  POSTGRES_PASSWORD       PostgreSQL password (default: nexus)
  MINIO_ROOT_PASSWORD     MinIO root password (default: minioadmin)

Example:
  sudo $0
  sudo $0 --prefix /usr/lib/systemd/system --user deploy --group deploy
EOF
  exit 0
}

# ── Parse args ────────────────────────────────────────────────────

PREFIX="/etc/systemd/system"
SVC_USER="${SUDO_USER:-$USER}"
SVC_GROUP="$(id -gn "$SVC_USER")"
WORKDIR="$ROOT"
ENV_ONLY=false
NO_START=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)   PREFIX="$2"; shift 2 ;;
    --user)     SVC_USER="$2"; shift 2 ;;
    --group)    SVC_GROUP="$2"; shift 2 ;;
    --workdir)  WORKDIR="$2"; shift 2 ;;
    --env-only) ENV_ONLY=true; shift ;;
    --no-start) NO_START=true; shift ;;
    --help)     usage ;;
    *)          err "Unknown option: $1"; usage ;;
  esac
done

# ── Preflight ─────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]] && [[ "$ENV_ONLY" != "true" ]]; then
  err "This script must be run as root for systemd installation (use sudo)."
  err "Or use --env-only to skip systemd steps."
  exit 1
fi

if ! command -v docker &>/dev/null; then
  err "docker is required but not found in PATH."
  exit 1
fi

# ── Generate .env ─────────────────────────────────────────────────

log "Generating .env ..."

if [[ -f "$ENV_FILE" ]]; then
  warn "$ENV_FILE already exists. Skipping generation."
  warn "Remove it manually if you want to regenerate: rm $ENV_FILE"
else
  cat > "$ENV_FILE" <<ENVEOF
# Nexus Systems — Environment Configuration
# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Nexus-Cloud
NEXUS_CLOUD_API_KEY=${NEXUS_CLOUD_API_KEY:-change-me}
NEXUS_CLOUD_URL=http://nexus-cloud:8787
NEXUS_CLOUD_DOMAIN=nexus.local
CORS_ORIGIN=*
NODE_ENV=production

# PostgreSQL
POSTGRES_URL=postgresql://nexus:${POSTGRES_PASSWORD:-nexus}@postgres:5432/nexus
POSTGRES_USER=nexus
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nexus}
POSTGRES_DB=nexus

# Redis
REDIS_URL=redis://redis:6379

# MinIO / S3
S3_ENDPOINT=http://minio:9000
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
S3_BUCKET=nexus

# Deployment (optional)
# CF_API_TOKEN=
# CF_ZONE_ID=
# SERVER_PUBLIC_IP=
ENVEOF
  log "Created $ENV_FILE"
  warn "Review $ENV_FILE and change NEXUS_CLOUD_API_KEY before production use."
fi

if [[ "$ENV_ONLY" == "true" ]]; then
  log ".env generation complete. Exiting."
  exit 0
fi

# ── Data directories ──────────────────────────────────────────────

log "Setting up data directories ..."

mkdir -p "$DATA_DIR"/{postgres/init,logs,pids}
chown -R "${SVC_USER}:${SVC_GROUP}" "$DATA_DIR" 2>/dev/null || true
chmod 755 "$DATA_DIR"
find "$DATA_DIR" -type d -exec chmod 755 {} \; 2>/dev/null || true
find "$DATA_DIR" -type f -exec chmod 644 {} \; 2>/dev/null || true

# ── Install systemd units ─────────────────────────────────────────

log "Installing systemd units to $PREFIX ..."

install_svc() {
  local src="$SYSTEMD_DIR/$1"
  local dst="$PREFIX/$1"
  if [[ ! -f "$src" ]]; then
    err "Source unit not found: $src"
    exit 1
  fi

  sed -e "s|%U|$SVC_USER|g" \
      -e "s|%G|$SVC_GROUP|g" \
      -e "s|%h/nexus-systems|$WORKDIR|g" \
      "$src" > "$dst"

  chmod 644 "$dst"
  log "  Installed $dst"
}

install_svc "nexus-cloud.service"
install_svc "nexus-app@.service"
install_svc "nexus-ecosystem.target"

log "Reloading systemd ..."
systemctl daemon-reload

log "Enabling nexus-cloud.service ..."
systemctl enable nexus-cloud.service

log "Enabling nexus-ecosystem.target ..."
systemctl enable nexus-ecosystem.target

log ""
log "Systemd units installed successfully."
log ""

# ── Start ─────────────────────────────────────────────────────────

if [[ "$NO_START" == "true" ]]; then
  log "Skipping service start (--no-start)."
  log ""
  log "To start manually:"
  log "  sudo systemctl start nexus-cloud.service"
  log "  sudo systemctl enable nexus-app@nexus-graphic.service --now"
  log "  # or start everything:"
  log "  sudo systemctl start nexus-ecosystem.target"
  exit 0
fi

log "Starting Nexus-Cloud ..."
systemctl start nexus-cloud.service
log "Cloud starting (this may take ~30s for infra health checks) ..."

log ""
log "To start graphics apps:"
log "  sudo systemctl enable nexus-app@nexus-graphic.service --now"
log "  sudo systemctl enable nexus-app@nexus-design.service --now"
log "  sudo systemctl enable nexus-app@nexus-draw.service --now"
log "  sudo systemctl enable nexus-app@nexus-photos.service --now"
log "  sudo systemctl enable nexus-app@nexus-video.service --now"
log ""
log "Or start all at once via the target (requires apps already enabled):"
log "  sudo systemctl start nexus-ecosystem.target"
log ""
log "Check status:"
log "  systemctl status nexus-cloud"
log "  docker compose -f $WORKDIR/docker-compose.yml ps"

exit 0
