import { randomUUID } from "node:crypto"; import { startHeartbeat } from "./cloud"; import { TerminalEngine } from "./terminal-engine";
function json(payload: unknown, status: number, headers?: Record<string, string>): Response { const body = JSON.stringify(payload); return new Response(body, { status, headers: { "content-type": "application/json; charset=utf-8", "x-request-id": randomUUID(), ...headers } }); }
export function createServer() { const port = Number(process.env.PORT || "3110"); const baseUrl = process.env.NEXUS_NEXUS_TERMINAL_BASE_URL || `http://localhost:${port}`; const startedAt = Date.now(); const engine = new TerminalEngine("data/terminal.sqlite");
  const server = Bun.serve({ port, async fetch(request) { const url = new URL(request.url); const path = url.pathname || "";
    if (request.method === "GET" && path === "/health") { return json({ service: "nexus-terminal", status: "ok", version: "v1", uptimeSeconds: Math.floor((Date.now() - startedAt) / 1000), timestamp: new Date().toISOString() }, 200); }
    if (request.method === "GET" && path === "/api/v1/status") { return json({ service: "nexus-terminal", status: "ready", capabilities: ["sessions","commands","terminal"], cloudIntegration: { enabled: (process.env["NEXUS_TERMINAL_ENABLE_CLOUD_INTEGRATION"] || "true") !== "false", cloudUrl: process.env.NEXUS_CLOUD_URL || "http://localhost:8787" } }, 200); }
    if (request.method === "GET" && path === "/api/v1/terminal/sessions") { const uid = url.searchParams.get("userId") || undefined; return json(engine.listSessions(uid), 200); }
    if (request.method === "POST" && path === "/api/v1/terminal/sessions") { const b = await request.json().catch(() => ({})) as any; if (!b.userId) return json({ error: "userId required" }, 400); return json(engine.createSession(b.userId, b.type || "shell"), 201); }
    if (request.method === "POST" && path === "/api/v1/terminal/sessions/end") { const b = await request.json().catch(() => ({})) as any; if (!b.id) return json({ error: "id required" }, 400); engine.endSession(b.id); return json({ ok: true }, 200); }
    if (request.method === "GET" && path === "/api/v1/terminal/commands") { const sid = url.searchParams.get("sessionId"); if (!sid) return json({ error: "sessionId required" }, 400); return json(engine.getSessionHistory(sid), 200); }
    if (request.method === "POST" && path === "/api/v1/terminal/commands") { const b = await request.json().catch(() => ({})) as any; if (!b.sessionId || !b.command) return json({ error: "sessionId and command required" }, 400); return json(engine.logCommand(b.sessionId, b.command, b.output || "", b.exitCode || 0), 201); }
    return json({ error: "not found" }, 404); } });
  console.log(`[nexus-terminal] Listening on port ${server.port}`); const stopHeartbeat = startHeartbeat(baseUrl); return { server, engine, close: () => { stopHeartbeat(); server.stop(); } }; }
